version: '3.8'

services:
  dashticz:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        tz: Europe/Amsterdam
    image: dashticz
    container_name: dashticz
    restart: unless-stopped
    ports:
      - 8082:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/var/www/html

